FROM python:3.8.13

# Set Python path environment variable
ENV PYTHONPATH=$PYTHONPATH:/src/

# 1. Copy the requirements.txt file to the image
COPY ./requirements.txt /src/requirements.txt

# Set working directory
WORKDIR /src

# 2. Install the dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# 3. Copy the content of the current directory to the image
COPY ./ /src/

# 4. Run the populate_db.py script
CMD ["python", "populate_db.py"]
